services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWERTY
      POSTGRES_DB: predprof
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: {}
